include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/**/*.gql.dart"
    - "lib/generated/**/*.dart"
    - "lib/generated/*.dart"

linter:
  rules:
    avoid_unnecessary_containers: true
    no_logic_in_create_state: true
    constant_identifier_names: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_function_literals_in_foreach_calls: false
    unawaited_futures: true
