name: architecto
description: Architecture playground
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # architecture
  flutter_riverpod: ^1.0.3

  # code generation
  freezed_annotation: ^1.1.0
  json_annotation: ^4.3.0

  # localization
  intl: ^0.17.0
  intl_utils: ^2.3.0

  # navigation
  go_router: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.3
  freezed: ^1.1.1
  dart_code_metrics: ^4.9.1

flutter:
  uses-material-design: true