name: bloc_sample
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # architecture
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  base:
    path: ../base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: