name: riverpod_sample
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # architecture
  flutter_riverpod: ^1.0.3

  # localization
  intl: ^0.17.0
  intl_utils: ^2.3.0

  # navigation
  go_router: 9.0.3

  # ui
  sliver_tools: ^0.2.12

  base:
    path: ../base

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  dart_code_metrics: ^4.9.1

flutter:
  uses-material-design: true